### ISSUE TITLE
Different Hotpep File Not Found error

### ISSUE THREAD

**Issue by jfoldi81** [linnabrown/run_dbcan#40] opened 2020-04-13 03:21 UTC
I ran the E. Coli test example on MacOS and it worked fine but am now working in an Ubuntu VM and am running into this issue:

cp: cannot stat 'Hotpep/EscheriaColiK12MG1655/Results/output.txt': No such file or directory
Traceback (most recent call last):
  File "run_dbcan.py", line 215, in <module>
    with open(outPath+'Hotpep.out') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_EscheriaColiK12MG1655/Hotpep.out'

My output file does not generate a Hotpep.out file, but the diamond.out and hmmer.out files are complete based on comparing them to when I ran on MacOS. I've checked all my folders/files and they're in the same place as they were on MacOS.
Any help is much appreciated and let me know if you'd like more info, thank you!

**Comment by linnabrown** [comment] 2020-04-29 23:03
what's your command line for Ubuntu VM and MacOS respectively ?

**Comment by linnabrown** [comment] 2020-04-30 14:50
I updated the readme.md for installation because it may be caused by the inconsistent virtual env. Please try the new commands. If you have more question please let me know.

**Comment by linnabrown** [comment] 2020-05-01 05:06
You said you don't have this issue now (https://github.com/linnabrown/run_dbcan/issues/45) so I will close this issue. Thanks a lot.

**Closed by linnabrown** 2020-05-01 05:06 UTC
