### ISSUE TITLE
DIAMOND version error 

### ISSUE THREAD

**Issue by AntoniaFeilden** [linnabrown/run_dbcan#152] opened 2024-01-16 16:43 UTC
I used `DIAMOND/2.1.0-GCC-11.3.0` (module on our HPC) and got the following error when trying to download the databases:

`Database was built with a different version of diamond as is incompatible.`

I also had to load a HMMER and BLAST+ module. I used the following command, specifying the environment directory path to install to to prevent it from installing to Miniconda which I do not have administrator rights to. 

`conda install dbcan -p /users/acf542/scratch/python_environments/envs/dbcan -c conda-forge -c bioconda`

**Comment by HaidYi** [comment] 2024-01-16 17:17
Hi @AntoniaFeilden , please specifying the path you want to save the environment

conda create -p <your/path/that/you/have/permission> -c conda-forge -c bioconda dbcan

And then, activate the conda environment like this

source activate <your/path/that/you/have/permission> 

or
conda activate  <your/path/that/you/have/permission> 

Please do not use the outdated Diamond in your HPC since our run_dbcan will automatically install newest version of Diamond.

**Comment by AntoniaFeilden** [comment] 2024-01-17 09:43
Hi @HaidYi ,

I can confirm I have done the above and still get errors during the install of the databases (when the `dbcan` environment is active). 

I activate the `dbcan` conda environment during the database install and get errors which imply BLAST+, DIAMOND and HMMER need to be installed separately (hence why I used the modules on HPC).  

Is there something I am doing wrong? If not, which versions of BLAST+, DIAMOND and HMMER should I use.

**Comment by AntoniaFeilden** [comment] 2024-01-17 10:27
Hi @HaidYi ,

Thank you very much for your quick response. I can confirm that I perform the steps above:

`conda create -p /users/acf542/scratch/python_environments/envs/dbcan python=3.8`
`conda activate dbcan`
`conda install dbcan -p /users/acf542/scratch/python_environments/envs/dbcan -c conda-forge -c bioconda`

The I use the the code on the **[Database installation command](https://dbcan.readthedocs.io/en/latest/user_guide/database_preparation.html)** page. 
Initially, I receive the following error: 
`-bash: makeblastdb: command not found`
This motivated the BLAST+ download.
Any ideas what could be happening? I will try and install it via pip now.

**Comment by AntoniaFeilden** [comment] 2024-01-17 11:03
Hi @HaidYi ,

Database download resolved - I used the following command:
`dbcan_build --cpus 8 --db-dir db --clean`

I had to `pip install requests `. Please can you confirm that this approach downloads the most recent versions of databases?

**Comment by linnabrown** [comment] 2024-01-17 15:30
Hi @AntoniaFeilden 

this code https://dbcan.readthedocs.io/en/latest/user_guide/database_preparation.html is totally the same as the dbcan_build.py. I really have no idea why `makeblastdb` does not work when you directly put it in your shell command. I deleted this database installation page and I already recommended user to use `dbcan_build` from installation page (https://dbcan.readthedocs.io/en/latest/installation.html) to build database.

**Comment by linnabrown** [comment] 2024-01-17 22:07
I added `requests` in dependencies now. Thank you for brining this out. I will update dbcan into 4.1.4 and will let you know.

**Comment by AntoniaFeilden** [comment] 2024-01-18 09:35
Hi @linnabrown,

Thank you very much for solving this issue! Please can you confirm the database versions downloaded via the `dbcan_build --cpus 8 --db-dir db --clean` command? Are they the same as those which were listed on the [Database download page](https://dbcan.readthedocs.io/en/latest/user_guide/database_preparation.html)?

Thank you @HaidYi and @linnabrown - got it working for now at least and as a job script on a HPC. 

Wishing you a good day!

**Comment by linnabrown** [comment] 2024-01-18 14:36
@AntoniaFeilden Hi, I confirmed that the version is totally the same but there is a bug in dbcan_build and we already fixed it. However, we are still waiting for the merge from bioconda. 

You can download run-dbcan 4.1.2 package and use 'pip install ."  to update the dbcan package.

**Comment by linnabrown** [comment] 2024-01-18 15:34
@AntoniaFeilden The bioconda manager merged my package into Bioconda as 4.1.3. Those issues are fixed in the new version. Please update the package using `conda install dbcan -c bioconda`. Thank you

**Closed** 2024-01-18 15:34 UTC
